export default function NewsPage() {
  return (
    <section className="page">
      <h1>News</h1>
      <p className="page-desc">
        Partner news and AI-generated analysis curated by ANN.
      </p>

      {/* Partner News */}
      <div className="section">
        <h2>Partner News</h2>

        <div className="news-card">
          <span className="tag">Economy</span>
          <h3>Federal Reserve signals potential rate adjustment in Q2 2026</h3>
          <p>Source: Reuters</p>
        </div>

        <div className="news-card">
          <span className="tag">Energy</span>
          <h3>Global renewable energy capacity exceeds projections</h3>
          <p>Source: Bloomberg</p>
        </div>
      </div>

      {/* AI News */}
      <div className="section">
        <h2>ANN AI News</h2>

        <div className="news-card ai">
          <span className="tag neon">AI Analysis</span>
          <h3>Why misinformation spreads faster during election cycles</h3>
          <p>
            Generated by ANN AI based on multi-source credibility analysis.
          </p>
        </div>
      </div>
    </section>
  );
}


export default function NewsDetailPage() {
  return (
    <section className="page">
      <h1>Federal Reserve signals potential rate adjustment</h1>
      <p className="page-desc">
        Credibility discussion powered by ANN
      </p>

      {/* Credibility Summary */}
      <div className="credibility-box">
        <strong>ANN Credibility Index</strong>
        <span className="score">84%</span>
        <p>Moderate consensus, expert-weighted</p>
      </div>

      {/* Discussion */}
      <div className="discussion">
        <h2>Public Discussion</h2>

        <div className="comment expert">
          <span className="badge expert">Expert</span>
          <strong>Dr. J. Kim (Economist)</strong>
          <p>
            The claim is directionally accurate but timing assumptions are weak.
          </p>
        </div>

        <div className="comment user">
          <strong>User123</strong>
          <p>
            Why do some sources say the hike is delayed?
          </p>
        </div>
      </div>

      {/* Comment Input */}
      <div className="comment-input">
        <textarea placeholder="Join the discussion..." />
        <button>Post Comment</button>
      </div>
    </section>
  );
}
